### ISSUE TITLE
Failed to load plugin unofficial-tailwindcss-plugin

### ISSUE THREAD

**Issue by icheered** [nicholas-wilcox/unofficial-tailwindcss-obsidian-plugin#5]
I'm not sure if I'm doing something wrong. Do I need to install other packages?
These are the steps I took
- I downloaded the latest release zip (0.3.0)
- Unzipped the file
- Placed the resulting folder in .obsidian/plugins
- Restart obsidian
- It then shows up under settings => community plugins => installed plugins
- Clicking the toggle to enable it gives the popup in the issue title 

I just found out you can write HTML/CSS in markdown and thus in Obsidian so my first thought was Tailwindcss, I really hope it will work :)

**Comment by nicholas-wilcox** [comment]
My apologies, it took me a while to revisit this project after the last minor release. Later today, I will briefly try and replicate the steps you took to see if I can figure out what went wrong.

I believe this happened because I failed to properly separate the name of this repository from the name of the plugin, AKA the "plugin ID". Obsidian specifies that the plugin ID should not contain the word "obsidian", but I wanted to make sure the GitHub repository included "obsidian" in the name.

If you rename the folder in `.obsidian/plugins` to `unofficial-tailwindcss-plugin`, then I believe the plugin should work. This is precisely what I will do, and if it solves the issue, then I know exactly what changes I need to make to ensure that no one else runs into the same problem.

I am about to go on a vacation, so the next chance I will have to address this is mid-September. However, I expect this to be a simple fix.

**Comment by nicholas-wilcox** [comment]
So I did change the name of the ZIP archive in the release, but I ran into another bug related to the snippets folder not existing in a new vault.

I'll look into this again in the future, but for now, I'll just make a note of it in this issue, and hold off on publishing release 0.3.1.

**Comment by gapmiss** [comment]
Not sure this is related, but I just installed on a fresh vault and I had to edit the `manifest.json` as:

```json
"id": "unofficial-tailwindcss-obsidian-plugin",
```

Also, as you noted, I had to create the snippets directory to successfully build the plugin.

**Comment by nicholas-wilcox** [comment]
right, this is the "opposite" fix compared to the one I did. However, Obsidian does not permit community plugins with `obsidian` in the ID on their platform ([source](https://docs.obsidian.md/Plugins/Releasing/Submit+your+plugin#Step+3+Submit+your+plugin+for+review))

I'll go through the Vault and Adapter APIs to see what the best way is to create a missing snippets folder. I could also just fail gracefully and provide some visual error message in the app and also add some instructions in the README.

**Comment by nicholas-wilcox** [comment]
I've released version 0.3.1, which includes two changes that should fix errors when using the plugin in new vaults. (I finally tested it properly myself!)

- The name of the ZIP archive in the release matches the ID of the plugin, which is `unofficial-tailwindcss-plugin`. This was an oversight on my part when writing the GitHub Workflow, and there is already a note in the Developer Notes section of the README about this for those who would clone the repository into a plugin directory.
- The plugin will confirm that a CSS snippets directory exists in the vault's configuration directory, and it will create the snippets directory if it does not exist.

Additionally, I noticed some Tailwind warnings when there were no Markdown files in a fresh vault (which means that the `content` options in the Tailwind configuration is empty). I added a check for this, and the plugin will skip the main routine if there isn't any content.

Note that Tailwind will still log a console warning if there _is_ content but no utility classes are found.

**Comment by nicholas-wilcox** [comment]
As I mentioned before, I'll be gone for a while after tomorrow. I'll leave this ticket open for @icheered to close (if they want to and this repository is configured correctly) once they confirm that they can use the plugin successfully. Otherwise, I'll close the ticket myself later in September.

**Comment by gapmiss** [comment]
Thank you for your quick attention to these minor issues. Really appreciated. Will upgrade with a fresh install later today and submit a new issue if there is anything I run into.

**Comment by jrtacoronte** [comment]
Good afternoon.
I have installed and enabled the Obsidian plugin "Hot Reloaded 0.1.10".
I have downloaded the latest version: "unofficial-tailwindcss-obsidian-plugin-main.zip" (0.3.1).
The zip file contains the folder "unofficial-tailwindcss-obsidian-plugin-main", which I copy into the Obsidian plugins folder: "...\.obsidian\plugins".
When I enable the Obsidian plugin it shows the message "Failed to load plugin unofficial-tailwindcss-plugin".

I also tried renaming the plugin folder from "unofficial-tailwindcss-obsidian-plugin-main" to "unofficial-tailwindcss-plugin", but that doesn't work either.

Any ideas?

Thanks.

**Comment by nicholas-wilcox** [comment]
@jrtacoronte based on the fact that you say you downloaded an archive named "unofficial-tailwindcss-obsidian-plugin-main.zip", I believe that you have actually downloaded an archive of the source code for this repository, rather than the compiled release.

If you have NodeJS installed, then you could potentially install the plugin's dependencies and build the application yourself. (See the notes at the bottom of the README for more information, especially concerning Tailwind's Preflight module.)

Otherwise, you should download the pre-built archive of the 0.3.1 release from here: https://github.com/nicholas-wilcox/unofficial-tailwindcss-obsidian-plugin/releases/tag/0.3.1.
